run:
#	gcc ./21_sorting_array_of_strings.c && ./a.out wkue qoi sbv fekls
	gcc ./21_sorting_array_of_strings.c && ./a.out bkmjbd aoxy l kdiacuhap bkctw uzcj fmog nglz y kagghgv hhibezx dioj dryqxjrc vohe rmsxuahx gwlmfav foaxllp vmeeszxf wztd zmwlydn fsjhpw gmqv u psskqteutd qqgtdbb mi idxutu q dkcoa swrxcjqkd lgtxokiu cpcp msroguma gyvpofsjt espoa ydaauimo cxvrxo vjmlqhxlhd y e
